version: '3.6'

services:
  timesheet-approve-service:
    image: ${DOCKER_REPO_URI}/${DOCKER_IMAGE}:${DOCKER_VERSION}
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAM=256m -XX:+UseSerialGC -Xss512k
